name: build
on: [pull_request, push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make

      - name: Run
        run: ./saplisten -h
